### ISSUE TITLE
Out-of-date / Remove from Bower

### ISSUE THREAD

**Issue by tysongach** [hmps/bourbon#4]
This fork of Bourbon and its package on Bower are out-of-date. [Bourbon](https://github.com/thoughtbot/bourbon)—the original project—is already published on Bower. Would you be up for removing this package from Bower to prevent confusion and better point people to the main Bourbon source?

**Comment by hmps** [comment]
@tysongach thanks for giving me a heads up here. I had completely forgotten about adding this to Bower. I have removed it now and will delete this repo shortly.

**Comment by tysongach** [comment]
@hmps Thank you!
